"Queries are for geting data from server. Read more [here](https://graphql.org/learn/queries/)."
type Query {
  "Returns list of authors."
  authors(status: Status): [Author]
  "Returns one author by id."
  author(id: ID!): Author
  "Returns list of blog posts."
  posts(last: Int = 3): [Post]
  "Returns one blog post by id."
  post(id: ID!): Post
}

type Author {
  id: ID!
  email: String
  name: String
  status: Status
  "Reference to author posts."
  posts: [Post]
}

type Post {
  id: ID!
  "Reference to post's author."
  author: Author!
  created_at(format: String): String!
  title: String
  body: String
  comments: [Comment]
}

type Comment {
  id: ID!
  post: Post!
  created_at: String!
  author: String
  body: String
}

enum Status {
  active
  inactive
}

"Mutations are for changing data in server. Read more [here](https://graphql.org/learn/queries/#mutations)."
type Mutation {
  "Creates new post."
  submitPost(author_id: Int!, title: String, body: String): Post
  "Creates new comment."
  submitComment(post_id: Int!, author: String, body: String): Comment
}
